'use strict';

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
const mysql = require('mysql2/promise');
const bcrypt = require('bcryptjs');

const REQUEST_TYPES = ['Instalação', 'Manutenção Preventiva', 'Auditoria'];
const ADMIN_USER = process.env.SEED_ADMIN_USER || 'admin';
const ADMIN_PASS = process.env.SEED_ADMIN_PASSWORD || 'admin';

const STATIONS = [
  {
    name: 'Torre Alphaville',
    code: 'TALPH-001',
    siteId: 'SITE-1001',
    elementType: 'Torre',
    technology: '4G',
    connectionType: 'Fibra Óptica',
    classification: '_MACRO',
    acquisitionDate: '2019-03-15',
    constructionDate: '2019-06-20',
    activationDate: '2019-08-01',
    status: 'Ativo',
    streetType: 'Avenida',
    street: 'Av. Pedro Ludovico Teixeira',
    number: '3000',
    neighborhood: 'Alphaville',
    city: 'Barueri',
    state: 'SP',
    zipCode: '06455-000',
    regional: 'Sudeste',
    latitude: '-23.4863',
    longitude: '-46.8525',
    towerType: 'Torre Autoportante',
    aevNominal: '45',
    groundArea: '250',
    structureHeight: '35',
    responsible: 'João Silva',
    phone: '(11) 99876-5432',
    email: 'joao.silva@exemplo.com',
    areaContractType: 'Locação',
    areaHolder: 'Imobiliária Alphaville',
    infraContractType: 'Própria',
    infraHolder: 'Operadora X',
    evType: 'Microcélula',
    evProvider: 'Fornecedor A',
    observation: 'Cobertura para complexo empresarial',
  },
  {
    name: 'Estação Centro SP',
    code: 'ECENT-002',
    siteId: 'SITE-1002',
    elementType: 'Estação',
    technology: '5G',
    connectionType: 'Fibra Óptica',
    classification: '_MACRO',
    acquisitionDate: '2021-01-10',
    constructionDate: '2021-04-05',
    activationDate: '2021-06-15',
    status: 'Ativo',
    streetType: 'Rua',
    street: 'Rua XV de Novembro',
    number: '150',
    neighborhood: 'Centro',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01013-000',
    regional: 'Sudeste',
    latitude: '-23.5505',
    longitude: '-46.6340',
    towerType: 'Poste Metálico',
    aevNominal: '30',
    groundArea: '120',
    structureHeight: '20',
    responsible: 'Maria Oliveira',
    phone: '(11) 98765-4321',
    email: 'maria.oliveira@exemplo.com',
    areaContractType: 'Concessão',
    areaHolder: 'Prefeitura de SP',
    infraContractType: 'Compartilhada',
    infraHolder: 'InfraCo',
    observation: 'Região de alta demanda',
  },
  {
    name: 'Torre Barra da Tijuca',
    code: 'TBARR-003',
    siteId: 'SITE-1003',
    elementType: 'Torre',
    technology: '4G',
    connectionType: 'Micro-ondas',
    classification: 'MACRO',
    acquisitionDate: '2018-07-22',
    constructionDate: '2018-10-10',
    activationDate: '2018-12-01',
    status: 'Ativo',
    streetType: 'Avenida',
    street: 'Av. das Américas',
    number: '5000',
    neighborhood: 'Barra da Tijuca',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22640-100',
    regional: 'Sudeste',
    latitude: '-22.9997',
    longitude: '-43.3646',
    towerType: 'Torre Autoportante',
    aevNominal: '50',
    groundArea: '300',
    structureHeight: '40',
    responsible: 'Carlos Pereira',
    phone: '(21) 99123-4567',
    email: 'carlos.pereira@exemplo.com',
    areaContractType: 'Locação',
    areaHolder: 'Shopping Barra',
    infraContractType: 'Própria',
    infraHolder: 'Operadora Y',
    towerType: 'Torre Autoportante',
    observation: 'Cobertura para zona comercial',
  },
  {
    name: 'Estação Lagoa Santa',
    code: 'ELAGO-004',
    siteId: 'SITE-1004',
    elementType: 'Estação',
    technology: '4G',
    connectionType: 'Fibra Óptica',
    classification: 'MICRO',
    acquisitionDate: '2020-05-18',
    constructionDate: '2020-08-12',
    activationDate: '2020-10-20',
    status: 'Ativo',
    streetType: 'Rua',
    street: 'Rua Minas Gerais',
    number: '456',
    neighborhood: 'Centro',
    city: 'Lagoa Santa',
    state: 'MG',
    zipCode: '33400-000',
    regional: 'Sudeste',
    latitude: '-19.6267',
    longitude: '-43.8900',
    towerType: 'Poste de Concreto',
    aevNominal: '25',
    groundArea: '80',
    structureHeight: '15',
    responsible: 'Ana Costa',
    phone: '(31) 98456-7890',
    email: 'ana.costa@exemplo.com',
    areaContractType: 'Permissão',
    areaHolder: 'Prefeitura Lagoa Santa',
    infraContractType: 'Compartilhada',
    infraHolder: 'TowerCo',
  },
  {
    name: 'Torre Recife Centro',
    code: 'TRECI-005',
    siteId: 'SITE-1005',
    elementType: 'Torre',
    technology: '4G',
    connectionType: 'Fibra Óptica',
    classification: 'MACRO',
    acquisitionDate: '2017-11-03',
    constructionDate: '2018-02-15',
    activationDate: '2018-04-10',
    status: 'Ativo',
    streetType: 'Avenida',
    street: 'Av. Conde da Boa Vista',
    number: '800',
    neighborhood: 'Boa Vista',
    city: 'Recife',
    state: 'PE',
    zipCode: '50060-002',
    regional: 'Nordeste',
    latitude: '-8.0476',
    longitude: '-34.8770',
    towerType: 'Torre Autoportante',
    aevNominal: '55',
    groundArea: '350',
    structureHeight: '45',
    responsible: 'Pedro Santos',
    phone: '(81) 99789-0123',
    email: 'pedro.santos@exemplo.com',
    areaContractType: 'Locação',
    areaHolder: 'Condomínio Boa Vista',
    infraContractType: 'Própria',
    infraHolder: 'Operadora Z',
    observation: 'Torre principal da região metropolitana',
  },
  {
    name: 'Estação Salvador Pituba',
    code: 'ESALV-006',
    siteId: 'SITE-1006',
    elementType: 'Estação',
    technology: '5G',
    connectionType: 'Fibra Óptica',
    classification: 'MACRO',
    acquisitionDate: '2022-02-28',
    constructionDate: '2022-05-15',
    activationDate: '2022-08-01',
    status: 'Ativo',
    streetType: 'Avenida',
    street: 'Av. ACM',
    number: '2000',
    neighborhood: 'Pituba',
    city: 'Salvador',
    state: 'BA',
    zipCode: '41720-200',
    regional: 'Nordeste',
    latitude: '-12.9667',
    longitude: '-38.4667',
    towerType: 'Torre Monopolo',
    aevNominal: '35',
    groundArea: '150',
    structureHeight: '30',
    responsible: 'Fernanda Lima',
    phone: '(71) 99345-6789',
    email: 'fernanda.lima@exemplo.com',
    areaContractType: 'Concessão',
    areaHolder: 'Prefeitura de Salvador',
    infraContractType: 'Própria',
    infraHolder: 'Operadora W',
  },
  {
    name: 'Torre Curitiba Batel',
    code: 'TCURI-007',
    siteId: 'SITE-1007',
    elementType: 'Torre',
    technology: '4G',
    connectionType: 'Fibra Óptica',
    classification: 'MACRO',
    acquisitionDate: '2019-09-12',
    constructionDate: '2019-12-01',
    activationDate: '2020-01-20',
    status: 'Ativo',
    streetType: 'Rua',
    street: 'Rua Batel',
    number: '1200',
    neighborhood: 'Batel',
    city: 'Curitiba',
    state: 'PR',
    zipCode: '80250-000',
    regional: 'Sul',
    latitude: '-25.4400',
    longitude: '-49.2800',
    towerType: 'Torre Autoportante',
    aevNominal: '40',
    groundArea: '200',
    structureHeight: '32',
    responsible: 'Roberto Almeida',
    phone: '(41) 99567-8901',
    email: 'roberto.almeida@exemplo.com',
    areaContractType: 'Locação',
    areaHolder: 'Edifício Batel Palace',
    infraContractType: 'Compartilhada',
    infraHolder: 'InfraCo Sul',
  },
  {
    name: 'Estação Porto Alegre Moinhos',
    code: 'EPORT-008',
    siteId: 'SITE-1008',
    elementType: 'Estação',
    technology: '4G',
    connectionType: 'Micro-ondas',
    classification: 'MACRO',
    acquisitionDate: '2020-03-08',
    constructionDate: '2020-06-20',
    activationDate: '2020-09-05',
    status: 'Ativo',
    streetType: 'Avenida',
    street: 'Av. Moinhos de Vento',
    number: '500',
    neighborhood: 'Moinhos de Vento',
    city: 'Porto Alegre',
    state: 'RS',
    zipCode: '90570-080',
    regional: 'Sul',
    latitude: '-30.0340',
    longitude: '-51.2070',
    towerType: 'Poste Metálico',
    aevNominal: '28',
    groundArea: '100',
    structureHeight: '18',
    responsible: 'Luciana Ferreira',
    phone: '(51) 99678-9012',
    email: 'luciana.ferreira@exemplo.com',
    areaContractType: 'Permissão',
    areaHolder: 'Prefeitura POA',
    infraContractType: 'Própria',
    infraHolder: 'Operadora X',
  },
  {
    name: 'Torre Goiânia Setor Central',
    code: 'TGOIA-009',
    siteId: 'SITE-1009',
    elementType: 'Torre',
    technology: '4G',
    connectionType: 'Fibra Óptica',
    classification: 'MACRO',
    acquisitionDate: '2018-04-17',
    constructionDate: '2018-07-30',
    activationDate: '2018-09-15',
    status: 'Ativo',
    streetType: 'Avenida',
    street: 'Av. Goiás',
    number: '600',
    neighborhood: 'Setor Central',
    city: 'Goiânia',
    state: 'GO',
    zipCode: '74013-010',
    regional: 'Centro-Oeste',
    latitude: '-16.6869',
    longitude: '-49.2648',
    towerType: 'Torre Autoportante',
    aevNominal: '48',
    groundArea: '280',
    structureHeight: '38',
    responsible: 'Marcos Souza',
    phone: '(62) 99890-1234',
    email: 'marcos.souza@exemplo.com',
    areaContractType: 'Locação',
    areaHolder: 'Shopping Center Central',
    infraContractType: 'Própria',
    infraHolder: 'Operadora Y',
  },
  {
    name: 'Estação Manaus Centro',
    code: 'EMANA-010',
    siteId: 'SITE-1010',
    elementType: 'Estação',
    technology: '4G',
    connectionType: 'Micro-ondas',
    classification: 'MICRO',
    acquisitionDate: '2021-06-25',
    constructionDate: '2021-09-10',
    activationDate: '2021-11-01',
    status: 'Ativo',
    streetType: 'Rua',
    street: 'Rua Ramos Ferreira',
    number: '900',
    neighborhood: 'Centro',
    city: 'Manaus',
    state: 'AM',
    zipCode: '69010-120',
    regional: 'Norte',
    latitude: '-3.1190',
    longitude: '-60.0217',
    towerType: 'Poste de Concreto',
    aevNominal: '22',
    groundArea: '70',
    structureHeight: '12',
    responsible: 'Patrícia Mendes',
    phone: '(92) 99012-3456',
    email: 'patricia.mendes@exemplo.com',
    areaContractType: 'Permissão',
    areaHolder: 'Prefeitura de Manaus',
    infraContractType: 'Compartilhada',
    infraHolder: 'TowerCo Norte',
  },
  {
    name: 'Torre Brasília Asa Sul',
    code: 'TBRAS-011',
    siteId: 'SITE-1011',
    elementType: 'Torre',
    technology: '5G',
    connectionType: 'Fibra Óptica',
    classification: 'MACRO',
    acquisitionDate: '2022-08-10',
    constructionDate: '2022-11-20',
    activationDate: '2023-01-15',
    status: 'Ativo',
    streetType: 'Avenida',
    street: 'Av. L2 Sul',
    number: '300',
    neighborhood: 'Asa Sul',
    city: 'Brasília',
    state: 'DF',
    zipCode: '70297-400',
    regional: 'Centro-Oeste',
    latitude: '-15.7940',
    longitude: '-47.8825',
    towerType: 'Torre Monopolo',
    aevNominal: '52',
    groundArea: '320',
    structureHeight: '42',
    responsible: 'Gabriel Rocha',
    phone: '(61) 99234-5678',
    email: 'gabriel.rocha@exemplo.com',
    areaContractType: 'Concessão',
    areaHolder: 'GDF',
    infraContractType: 'Própria',
    infraHolder: 'Operadora Z',
    observation: 'Cobertura para esplanada dos ministérios',
  },
  {
    name: 'Estação Belém Marco',
    code: 'EBELE-012',
    siteId: 'SITE-1012',
    elementType: 'Estação',
    technology: '4G',
    connectionType: 'Fibra Óptica',
    classification: 'MACRO',
    acquisitionDate: '2020-11-05',
    constructionDate: '2021-02-18',
    activationDate: '2021-04-10',
    status: 'Ativo',
    streetType: 'Avenida',
    street: 'Av. Presidente Vargas',
    number: '1500',
    neighborhood: 'Marco',
    city: 'Belém',
    state: 'PA',
    zipCode: '66023-000',
    regional: 'Norte',
    latitude: '-1.4558',
    longitude: '-48.5024',
    towerType: 'Torre Autoportante',
    aevNominal: '42',
    groundArea: '260',
    structureHeight: '36',
    responsible: 'Diego Nascimento',
    phone: '(91) 99456-7890',
    email: 'diego.nascimento@exemplo.com',
    areaContractType: 'Locação',
    areaHolder: 'Condomínio Marco',
    infraContractType: 'Compartilhada',
    infraHolder: 'InfraCo Norte',
  },
  {
    name: 'Torre Fortaleza Aldeota',
    code: 'TFORT-013',
    siteId: 'SITE-1013',
    elementType: 'Torre',
    technology: '4G',
    connectionType: 'Fibra Óptica',
    classification: 'MACRO',
    acquisitionDate: '2019-01-20',
    constructionDate: '2019-04-15',
    activationDate: '2019-06-20',
    status: 'Inativo',
    deactivationDate: '2024-08-10',
    streetType: 'Avenida',
    street: 'Av. Beira Mar',
    number: '2000',
    neighborhood: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
    zipCode: '60165-120',
    regional: 'Nordeste',
    latitude: '-3.7320',
    longitude: '-38.5267',
    towerType: 'Torre Autoportante',
    aevNominal: '38',
    groundArea: '220',
    structureHeight: '34',
    responsible: 'Sandra Vieira',
    phone: '(85) 99567-8901',
    email: 'sandra.vieira@exemplo.com',
    areaContractType: 'Locação',
    areaHolder: 'Hotel Beira Mar',
    infraContractType: 'Própria',
    infraHolder: 'Operadora X',
    observation: 'Desativada por reestruturação da rede',
  },
  {
    name: 'Estação Campinas Cambuí',
    code: 'ECAMP-014',
    siteId: 'SITE-1014',
    elementType: 'Estação',
    technology: '4G',
    connectionType: 'Fibra Óptica',
    classification: 'MACRO',
    acquisitionDate: '2020-08-12',
    constructionDate: '2020-11-25',
    activationDate: '2021-01-10',
    status: 'Ativo',
    streetType: 'Rua',
    street: 'Rua Barão de Jaguara',
    number: '700',
    neighborhood: 'Cambuí',
    city: 'Campinas',
    state: 'SP',
    zipCode: '13013-140',
    regional: 'Sudeste',
    latitude: '-22.9043',
    longitude: '-47.0653',
    towerType: 'Poste Metálico',
    aevNominal: '32',
    groundArea: '130',
    structureHeight: '22',
    responsible: 'Renato Campos',
    phone: '(19) 99678-9012',
    email: 'renato.campos@exemplo.com',
    areaContractType: 'Permissão',
    areaHolder: 'Prefeitura Campinas',
    infraContractType: 'Compartilhada',
    infraHolder: 'TowerCo SP',
  },
  {
    name: 'Torre Vitória Centro',
    code: 'TVITO-015',
    siteId: 'SITE-1015',
    elementType: 'Torre',
    technology: '4G',
    connectionType: 'Micro-ondas',
    classification: 'MACRO',
    acquisitionDate: '2018-12-01',
    constructionDate: '2019-03-10',
    activationDate: '2019-05-05',
    status: 'Manutenção',
    streetType: 'Avenida',
    street: 'Av. Princesa Isabel',
    number: '1000',
    neighborhood: 'Centro',
    city: 'Vitória',
    state: 'ES',
    zipCode: '29015-440',
    regional: 'Sudeste',
    latitude: '-20.3155',
    longitude: '-40.3128',
    towerType: 'Torre Autoportante',
    aevNominal: '44',
    groundArea: '270',
    structureHeight: '37',
    responsible: 'Camila Dias',
    phone: '(27) 99789-0123',
    email: 'camila.dias@exemplo.com',
    areaContractType: 'Locação',
    areaHolder: 'Shopping Vitória',
    infraContractType: 'Própria',
    infraHolder: 'Operadora Y',
    observation: 'Em manutenção preventiva agendada',
  },
];

async function main() {
  const connection = await mysql.createConnection({
    host: process.env.DB_HOST || 'localhost',
    port: Number(process.env.DB_PORT || 3306),
    user: process.env.DB_USER || 'app',
    password: process.env.DB_PASSWORD || 'appsecret',
    database: process.env.DB_NAME || 'ticket_triage',
  });

  try {
    for (const name of REQUEST_TYPES) {
      await connection.query(
        `INSERT INTO request_types (id, name) VALUES (UUID(), ?)
         ON DUPLICATE KEY UPDATE name = VALUES(name)`,
        [name],
      );
    }
    console.log('Seed: tipos de solicitação garantidos.');

    const hash = await bcrypt.hash(ADMIN_PASS, 10);
    await connection.query(
      `INSERT INTO users (id, username, password_hash, must_change_password, role) VALUES (UUID(), ?, ?, TRUE, 'admin')
       ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), must_change_password = TRUE, role = 'admin'`,
      [ADMIN_USER, hash],
    );
    console.log(
      `Seed: usuário "${ADMIN_USER}" criado/atualizado (troca de senha obrigatória no primeiro login).`,
    );

    let insertedStations = 0;
    let updatedStations = 0;
    for (const s of STATIONS) {
      const [result] = await connection.query(
        `INSERT INTO stations (
          id, name, code, site_id, element_type, technology, connection_type,
          classification, acquisition_date, construction_date, activation_date,
          deactivation_date, status, street_type, street, number, neighborhood,
          city, state, zip_code, regional, latitude, longitude, tower_type,
          aev_nominal, ground_area, structure_height, responsible, phone, email,
          area_contract_type, area_holder, infra_contract_type, infra_holder,
          ev_type, ev_provider, observation
        ) VALUES (
          UUID(), ?, ?, ?, ?, ?, ?,
          ?, ?, ?, ?,
          ?, ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?, ?,
          ?, ?, ?, ?,
          ?, ?, ?, ?
        )
        ON DUPLICATE KEY UPDATE
          name = VALUES(name), site_id = VALUES(site_id),
          element_type = VALUES(element_type), technology = VALUES(technology),
          connection_type = VALUES(connection_type), classification = VALUES(classification),
          acquisition_date = VALUES(acquisition_date), construction_date = VALUES(construction_date),
          activation_date = VALUES(activation_date), deactivation_date = VALUES(deactivation_date),
          status = VALUES(status), street_type = VALUES(street_type),
          street = VALUES(street), number = VALUES(number),
          neighborhood = VALUES(neighborhood), city = VALUES(city),
          state = VALUES(state), zip_code = VALUES(zip_code),
          regional = VALUES(regional), latitude = VALUES(latitude),
          longitude = VALUES(longitude), tower_type = VALUES(tower_type),
          aev_nominal = VALUES(aev_nominal), ground_area = VALUES(ground_area),
          structure_height = VALUES(structure_height), responsible = VALUES(responsible),
          phone = VALUES(phone), email = VALUES(email),
          area_contract_type = VALUES(area_contract_type), area_holder = VALUES(area_holder),
          infra_contract_type = VALUES(infra_contract_type), infra_holder = VALUES(infra_holder),
          ev_type = VALUES(ev_type), ev_provider = VALUES(ev_provider),
          observation = VALUES(observation)`,
        [
          s.name, s.code, s.siteId, s.elementType, s.technology, s.connectionType,
          s.classification, s.acquisitionDate, s.constructionDate, s.activationDate,
          s.deactivationDate || null, s.status, s.streetType, s.street, s.number,
          s.neighborhood, s.city, s.state, s.zipCode, s.regional,
          s.latitude, s.longitude, s.towerType, s.aevNominal, s.groundArea,
          s.structureHeight, s.responsible, s.phone, s.email,
          s.areaContractType, s.areaHolder, s.infraContractType, s.infraHolder,
          s.evType || null, s.evProvider || null, s.observation || null,
        ],
      );
      if (result.affectedRows === 1) insertedStations++;
      else updatedStations++;
    }
    console.log(
      `Seed: ${STATIONS.length} estações garantidas (${insertedStations} inseridas, ${updatedStations} atualizadas).`,
    );
  } finally {
    await connection.end();
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
